from __future__ import annotations

from collections.abc import Callable, Iterator
from typing import Any, TypeVar

_T = TypeVar("_T")


class H:
    total: int

    def __init__(self, items: Any) -> None: ...
    def __add__(self, other: H) -> H: ...
    def __neg__(self) -> H: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

    def items(self) -> Iterator[tuple[Any, int]]: ...
    def outcomes(self) -> Iterator[Any]: ...
    def distribution(self, rational_t: Callable[[int, int], _T] | None = ...) -> Iterator[tuple[Any, _T]]: ...

    def mean(self) -> float: ...
    def variance(self) -> float: ...
    def stdev(self) -> float: ...
    def roll(self) -> int: ...
    def umap(self, un_op: Callable[[Any], Any]) -> H: ...
