from __future__ import annotations

from typing import Any

from .h import H


class P:
    def __init__(self, args: int | P | H) -> None: ...
    def h(self, *which: int | slice) -> H: ...
    def __rmatmul__(self, left: int) -> P: ...
    def roll(self) -> tuple[Any, ...]: ...
